### Login as admin-user and save the adminToken for usage in other requests
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

> {%
    client.global.set("adminToken", response.body.token);
%}

### GET information on authenticated user
GET http://localhost:8080/api/users/me
Authorization: Bearer {{adminToken}}

### Get all users (Admin only)
GET http://localhost:8080/api/users
Authorization: Bearer {{adminToken}}

### Get user with ID
GET http://localhost:8080/api/users/2
Authorization: Bearer {{adminToken}}

### Update the role of user to OFFICIAL
PUT http://localhost:8080/api/users/2/role
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "role": "OFFICIAL"
}

### Get updated user again and see that the role is promoted to OFFICIAL
GET http://localhost:8080/api/users/2
Authorization: Bearer {{adminToken}}

### DELETE a user
DELETE http://localhost:8080/api/users/2
Authorization: Bearer {{adminToken}}

### Get all reported incidents (Admin only)
GET http://localhost:8080/api/incidents
Authorization: Bearer {{adminToken}}

### Get paginated incidents list
GET http://localhost:8080/api/incidents/paginated?page=1&pageSize=5
Authorization: Bearer {{adminToken}}

### Get incidents reported by current admin
GET http://localhost:8080/api/incidents/my-incidents
Authorization: Bearer {{adminToken}}

### Get incident with ID
GET http://localhost:8080/api/incidents/1
Authorization: Bearer {{adminToken}}

### Update incident details
PUT http://localhost:8080/api/incidents/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "category": "COMMUNAL",
  "description": "Updated incident description by admin"
}

### Update priority of incident to CRITICAL
PATCH http://localhost:8080/api/incidents/1/priority
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "priority": "CRITICAL"
}

### Change status of incident to RESOLVED
PATCH http://localhost:8080/api/incidents/1/status
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "status": "RESOLVED"
}

### Get updated incident and verify resolved status
GET http://localhost:8080/api/incidents/1
Authorization: Bearer {{adminToken}}

### DELETE an incident
DELETE http://localhost:8080/api/incidents/14
Authorization: Bearer {{adminToken}}
