ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [
            avans.avd.ApplicationKt.module,
        ]
    }
}
jwt {
    audience = "ktor-incident-api"
    audience = ${?JWT_AUDIENCE}

    issuer = "http://localhost:8080"
    issuer = ${?JWT_ISSUER}

    realm = "Incidents API"
    secret = "my secret"
    secret = ${?JWT_SECRET}
}
