### Login as a municipal official and save officialToken for usage in other requests
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "Ron",
  "password": "pwd"
}

> {%
    client.global.set("officialToken", response.body.token);
%}

### GET information on authenticated user
GET http://localhost:8080/api/users/me
Authorization: Bearer {{officialToken}}


### Get all reported incidents
GET http://localhost:8080/api/incidents
Authorization: Bearer {{officialToken}}

### Get all incidents reported by user with ID=2 (Henk)
GET http://localhost:8080/api/users/2/incidents
Authorization: Bearer {{officialToken}}

### Get incident with ID=1 and see the priority=HIGH and status=ASSIGNED
GET http://localhost:8080/api/incidents/1
Authorization: Bearer {{officialToken}}

> {%
    client.global.set("incidentIdToTestPutAndPatch", response.body.id);
%}

### Change incident status to ASSIGNED
PATCH http://localhost:8080/api/incidents/1/status
Content-Type: application/json
Authorization: Bearer {{officialToken}}

{
  "status": "ASSIGNED"
}

### Update pririty of incident with ID=1 to CRITICAL
### PATCH the priority of this incident to CRITICAL
PATCH http://localhost:8080/api/incidents/{{incidentIdToTestPutAndPatch}}/priority
Content-Type: application/json
Authorization: Bearer {{officialToken}}

{
  "priority": "CRITICAL"
}


### Change the status of this incident to RESOLVED
PATCH http://localhost:8080/api/incidents/{{incidentIdToTestPutAndPatch}}/status
Content-Type: application/json
Authorization: Bearer {{officialToken}}

{
  "status": "RESOLVED"
}


### Get incident with same and see the new status= RESOLVED
GET http://localhost:8080/api/incidents/{{incidentIdToTestPutAndPatch}}
Authorization: Bearer {{officialToken}}

### Get paginated incidents list
GET http://localhost:8080/api/incidents/paginated?page=2&pageSize=3
Authorization: Bearer {{officialToken}}

