package avans.avd.incidents

import avans.avd.users.UserRepository

/**
 * Demo incidents, expressed as plain domain objects: they carry [Incident.NEW_INCIDENT_ID],
 * so every repository implementation is free to generate its own ids.
 *
 * The reporter is looked up by username via [userIdOf] instead of being hard-coded, because the
 * user ids are generated by the user repository (in-memory counter, database sequence, ...).
 * An unknown username yields `null`, which the domain interprets as an anonymous report.
 */
fun demoIncidents(userIdOf: (username: String) -> Long?): List<Incident> = listOf(
    Incident(
        userIdOf("Anne"),
        Category.TRAFFIC,
        "Sink hole here. Dangerous situation! Quick fix needed.",
        51.58677130730741,
        4.808487370673,
        Priority.HIGH,
        Status.ASSIGNED
    ),
    Incident(
        userIdOf("Henk"),
        Category.COMMUNAL,
        "At this corner 2 lights are broken",
        51.59051650746655,
        4.812002566502519,
        Priority.NORMAL
    ),
    Incident(
        userIdOf("Henk"),
        Category.COMMUNAL,
        "noise disturbance from illegal party",
        51.58218477578439,
        4.835727885428926,
        Priority.NORMAL
    ),
    Incident(
        userIdOf("Anne"),
        Category.ENVIRONMENT,
        "Some xtc lab dumped chemicals. ",
        51.58907773104348,
        4.80552621192238,
        Priority.HIGH
    ),
    // Realistic incidents around Breda (within ~3km radius of 51.5898, 4.7832)
    Incident(
        userIdOf("Bram"),
        Category.COMMUNAL,
        "Loose paving stones causing trips near playground",
        51.5921,
        4.7789,
        Priority.NORMAL,
        Status.REPORTED
    ),
    Incident(
        userIdOf("Fatima"),
        Category.TRAFFIC,
        "Pothole forming at intersection; cyclists swerving to avoid it",
        51.5853,
        4.7897,
        Priority.HIGH,
        Status.ASSIGNED
    ),
    Incident(
        userIdOf("Lotte"),
        Category.ENVIRONMENT,
        "Illegal dumping: several garbage bags in the bushes",
        51.5945,
        4.7923,
        Priority.NORMAL,
        Status.REPORTED
    ),
    Incident(
        null /*anonymous*/,
        Category.CRIME,
        "Bike theft attempt reported by neighbors last night",
        51.5839,
        4.7752,
        Priority.LOW,
        Status.REPORTED
    ),
    Incident(
        null /*anonymous*/,
        Category.OTHER,
        "Graffiti on underpass wall freshly painted over but still visible",
        51.5884,
        4.8011,
        Priority.LOW,
        Status.RESOLVED
    ),
    // Incidents reported by the official Ron
    Incident(
        userIdOf("Ron"),
        Category.TRAFFIC,
        "Traffic light stuck on red causing delays at small junction",
        51.5902,
        4.7841,
        Priority.HIGH,
        Status.ASSIGNED
    ),
    Incident(
        userIdOf("Ron"),
        Category.COMMUNAL,
        "Streetlight out along park path; dark spot reported by residents",
        51.5876,
        4.7805,
        Priority.NORMAL,
        Status.REPORTED
    ),
    Incident(
        userIdOf("Ron"),
        Category.ENVIRONMENT,
        "Fallen branch blocking part of the bike lane; cleared by contractor",
        51.5930,
        4.7872,
        Priority.NORMAL,
        Status.RESOLVED
    ),
    Incident(
        userIdOf("Ron"),
        Category.OTHER,
        "Damaged yield sign at side street; pole bent, sign still readable",
        51.5869,
        4.7920,
        Priority.LOW,
        Status.REPORTED
    )
)

/**
 * Seeds demo data through the [IncidentRepository] interface, so the very same function works for
 * the in-memory fake and for a persistent (Exposed) implementation.
 *
 * Schema creation, transaction handling and id generation are deliberately left to the
 * implementation. Seeding is idempotent: an already populated repository is left untouched.
 */
suspend fun IncidentRepository<Long>.seedDemoData(incidents: List<Incident>): List<Incident> {
    if (findAll().isNotEmpty()) return emptyList()
    return saveAll(incidents)
}

/**
 * Convenience overload that resolves the reporters from an already seeded [userRepository],
 * so seed the users first.
 */
suspend fun IncidentRepository<Long>.seedDemoData(userRepository: UserRepository<Long>): List<Incident> {
    val idsByUsername = userRepository.findAll().associate { it.username to it.id }
    return seedDemoData(demoIncidents { username -> idsByUsername[username] })
}
