### Login as admin-user and save the adminToken for usage in other requests
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

> {%
    client.global.set("adminToken", response.body.token);
%}

### GET information on authenticated user
GET http://localhost:8080/api/users/me
Authorization: Bearer {{adminToken}}

### Get all users (Admin only)
GET http://localhost:8080/api/users
Authorization: Bearer {{adminToken}}

### Get user with ID
GET http://localhost:8080/api/users/2
Authorization: Bearer {{adminToken}}

### Update the role of user to OFFICIAL
PUT http://localhost:8080/api/users/2/role
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "role": "OFFICIAL"
}

### Get updated user again and see that the role is promoted to OFFICER
GET http://localhost:8080/api/users/2
Authorization: Bearer {{adminToken}}

### DELETE a user
DELETE http://localhost:8080/api/users/2
Authorization: Bearer {{adminToken}}
